name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HRKU-0666f925-b962-4a74-92f6-d45118c2617c }}
      run: |
        git remote add heroku https://git.heroku.com/cloudtester.git
        git push heroku main

